---
# Cockpit security configuration

# Generate /etc/cockpit/cockpit.conf with the CIS session idle timeout
- name: Deploy /etc/cockpit/cockpit.conf configuration template
  ansible.builtin.template:
    src: cockpit.conf.j2
    dest: /etc/cockpit/cockpit.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart cockpit.socket
